#!/bin/bash

COMMIT_MSG=${1:-"🔧 Update changes"}

if git pull && git add . && git commit -m "$COMMIT_MSG" && git push; then
    echo -e "\033[0;32mOK\033[0m"   
else
    echo -e "\033[0;31mFAIL\033[0m" 
fi
